// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Perdin.WebApi.Data;

#nullable disable

namespace Perdin.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710065428_MakeApproverIdNullableAndAddProvinceIsland")]
    partial class MakeApproverIdNullableAndAddProvinceIsland
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Perdin.WebApi.Models.BusinessTripRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("departure_date");

                    b.Property<int?>("DestinationCityId")
                        .HasColumnType("int")
                        .HasColumnName("destination_city_id");

                    b.Property<int>("DestinationCountryId")
                        .HasColumnType("int")
                        .HasColumnName("destination_country_id");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_days");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int")
                        .HasColumnName("origin_city_id");

                    b.Property<int>("PocketMoney")
                        .HasColumnType("int")
                        .HasColumnName("pocket_money");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("request_number");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("reviewed")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("DestinationCountryId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("business_trip_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessTrip_Status", "status IN ('reviewed','rejected','approved')");
                        });
                });

            modelBuilder.Entity("Perdin.WebApi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -6.1805m,
                            Longitude = 106.8284m,
                            Name = "Jakarta Pusat",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -6.2615m,
                            Longitude = 106.8106m,
                            Name = "Jakarta Selatan",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -6.9175m,
                            Longitude = 107.6191m,
                            Name = "Bandung",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -6.5971m,
                            Longitude = 106.7932m,
                            Name = "Bogor",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -6.9667m,
                            Longitude = 110.4167m,
                            Name = "Semarang",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -7.5667m,
                            Longitude = 110.8167m,
                            Name = "Surakarta",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -7.7956m,
                            Longitude = 110.3695m,
                            Name = "Yogyakarta",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -7.2504m,
                            Longitude = 112.7688m,
                            Name = "Surabaya",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -7.9839m,
                            Longitude = 112.6214m,
                            Name = "Malang",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -6.1702m,
                            Longitude = 106.6403m,
                            Name = "Tangerang",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -8.6705m,
                            Longitude = 115.2126m,
                            Name = "Denpasar",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 3.5952m,
                            Longitude = 98.6722m,
                            Name = "Medan",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 3.1390m,
                            Longitude = 101.6869m,
                            Name = "Kuala Lumpur City",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 3.1073m,
                            Longitude = 101.6067m,
                            Name = "Petaling Jaya",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 1.3521m,
                            Longitude = 103.8198m,
                            Name = "Singapore City",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 13.7563m,
                            Longitude = 100.5018m,
                            Name = "Bangkok City",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 35.6938m,
                            Longitude = 139.7034m,
                            Name = "Shinjuku",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 37.4979m,
                            Longitude = 127.0276m,
                            Name = "Gangnam",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 34.0522m,
                            Longitude = -118.2437m,
                            Name = "Los Angeles",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 51.5074m,
                            Longitude = -0.1278m,
                            Name = "London City",
                            ProvinceId = 20
                        });
                });

            modelBuilder.Entity("Perdin.WebApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsForeign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_foreign");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = false,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Singapura"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Filipina"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Jepang"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Korea Selatan"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "China"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Amerika Serikat"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Inggris"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Jerman"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Perancis"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Belanda"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Selandia Baru"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Arab Saudi"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "Uni Emirat Arab"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsForeign = true,
                            Name = "India"
                        });
                });

            modelBuilder.Entity("Perdin.WebApi.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Island")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("island");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Jawa",
                            Name = "DKI Jakarta"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Jawa",
                            Name = "Jawa Barat"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Jawa",
                            Name = "Jawa Tengah"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Jawa",
                            Name = "DI Yogyakarta"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Jawa",
                            Name = "Jawa Timur"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Jawa",
                            Name = "Banten"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Bali",
                            Name = "Bali"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Sumatera",
                            Name = "Sumatera Utara"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Kuala Lumpur"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Selangor"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Central Singapore"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Hanoi"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Metro Manila"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "California"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Island = "Luar Negeri",
                            Name = "Greater London"
                        });
                });

            modelBuilder.Entity("Perdin.WebApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PEGAWAI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SDM"
                        });
                });

            modelBuilder.Entity("Perdin.WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rudi@gmail.com",
                            Name = "Rudi Hartono",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "rudi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "siti@gmail.com",
                            Name = "Siti Nurhaliza",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "siti"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "budi@gmail.com",
                            Name = "Budi Santoso",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "budi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andi@gmail.com",
                            Name = "Andi Prasetyo",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "andi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dewi@gmail.com",
                            Name = "Dewi Lestari",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "dewi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eko@gmail.com",
                            Name = "Eko Wibowo",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "eko"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fitri@gmail.com",
                            Name = "Fitri Handayani",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "fitri"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gunawan@gmail.com",
                            Name = "Gunawan Putra",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "gunawan"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hana@gmail.com",
                            Name = "Hana Permata",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "hana"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "irfan@gmail.com",
                            Name = "Irfan Maulana",
                            Password = "$2a$11$xTpqaQGkrP1q6EwUAVyAceZFAFmfs8Bz4jiDYaFqHG9s1dwvyeZIC",
                            Username = "irfan"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            RolesId = 2,
                            UsersId = 2
                        },
                        new
                        {
                            RolesId = 3,
                            UsersId = 3
                        },
                        new
                        {
                            RolesId = 2,
                            UsersId = 4
                        },
                        new
                        {
                            RolesId = 1,
                            UsersId = 4
                        },
                        new
                        {
                            RolesId = 2,
                            UsersId = 5
                        },
                        new
                        {
                            RolesId = 3,
                            UsersId = 5
                        },
                        new
                        {
                            RolesId = 2,
                            UsersId = 6
                        },
                        new
                        {
                            RolesId = 1,
                            UsersId = 7
                        },
                        new
                        {
                            RolesId = 2,
                            UsersId = 8
                        },
                        new
                        {
                            RolesId = 3,
                            UsersId = 8
                        },
                        new
                        {
                            RolesId = 3,
                            UsersId = 9
                        },
                        new
                        {
                            RolesId = 2,
                            UsersId = 10
                        },
                        new
                        {
                            RolesId = 1,
                            UsersId = 10
                        });
                });

            modelBuilder.Entity("Perdin.WebApi.Models.BusinessTripRequest", b =>
                {
                    b.HasOne("Perdin.WebApi.Models.User", "Approver")
                        .WithMany("BusinessTripRequestsAsApprover")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_BusinessTrip_Approver");

                    b.HasOne("Perdin.WebApi.Models.City", "DestinationCity")
                        .WithMany("BusinessTripRequestsAsDestination")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_BusinessTrip_DestinationCity");

                    b.HasOne("Perdin.WebApi.Models.Country", "DestinationCountry")
                        .WithMany("BusinessTripRequests")
                        .HasForeignKey("DestinationCountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BusinessTrip_DestinationCountry");

                    b.HasOne("Perdin.WebApi.Models.City", "OriginCity")
                        .WithMany("BusinessTripRequestsAsOrigin")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BusinessTrip_OriginCity");

                    b.HasOne("Perdin.WebApi.Models.User", "User")
                        .WithMany("BusinessTripRequestsAsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BusinessTrip_User");

                    b.Navigation("Approver");

                    b.Navigation("DestinationCity");

                    b.Navigation("DestinationCountry");

                    b.Navigation("OriginCity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Perdin.WebApi.Models.City", b =>
                {
                    b.HasOne("Perdin.WebApi.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Cities_Provinces");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Perdin.WebApi.Models.Province", b =>
                {
                    b.HasOne("Perdin.WebApi.Models.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Provinces_Countries");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Perdin.WebApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Perdin.WebApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Perdin.WebApi.Models.City", b =>
                {
                    b.Navigation("BusinessTripRequestsAsDestination");

                    b.Navigation("BusinessTripRequestsAsOrigin");
                });

            modelBuilder.Entity("Perdin.WebApi.Models.Country", b =>
                {
                    b.Navigation("BusinessTripRequests");

                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Perdin.WebApi.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Perdin.WebApi.Models.User", b =>
                {
                    b.Navigation("BusinessTripRequestsAsApprover");

                    b.Navigation("BusinessTripRequestsAsUser");
                });
#pragma warning restore 612, 618
        }
    }
}
